#$(CC),$(MV) are inherited from the parent Makefile
all:
	$(CC) -o Image_processor.o -c Image_processor.cpp $(CPPFLAGS)
	echo "Image_processor.o: moving to parent directory intel_board"
	$(MV) Image_processor.o ../